version: "3.7"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/:/code/
    ports:
      - 5000:5000
    command: ./entrypoint.sh
    environment:
      APP_PORT: 5000

  db:
    image: redis:alpine3.13
